#!/bin/sh
# /etc/init.d/powerbot-daemon

### BEGIN INIT INFO
# Provides:          powerbot
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start or stop the powerbot.
### END INIT INFO

case "$1" in
	start)
		echo "Starting powerbot service..."
		python /opt/powerbot/powerbot.py start
		;;
	stop)
		echo "Stopping powerbot service..."
		python /opt/powerbot/powerbot.py stop
		;;
	restart)
		echo "Restarting powerbot service..."
		python /opt/powerbot/powerbot.py restart
		;;
	*)
		echo "Usage: /etc/init.d/powerbot (start|stop|restart)"
		exit 1
		;;
esac

exit 0