#!/bin/sh
# /etc/init.d/tirukkural-daemon

### BEGIN INIT INFO
# Provides:          tirukkural
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start or stop the tirukkural.
### END INIT INFO

case "$1" in
	start)
		echo "Starting tirukkural service..."
		python /opt/tirukkural/tirukkural.py start
		;;
	stop)
		echo "Stopping tirukkural service..."
		python /opt/tirukkural/powerbot.py stop
		;;
	restart)
		echo "Restarting tirukkural service..."
		python /opt/tirukkural/powerbot.py restart
		;;
	*)
		echo "Usage: /etc/init.d/tirukkural (start|stop|restart)"
		exit 1
		;;
esac

exit 0